export const items = {
  1: {
    id: 1,
    name: "Women’s Teal Blue Flared Anarkali Kurti with Lace Sleeves",
    price: "₹549",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1-1.webp",
    ],
    desc: "Attractive women dress in crepe fabric with lace inserts. Fit and flare maxi dress with V-neck and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Crepe",
      "Fit/Shape: Fit and Flare",
      "Length: Maxi",
      "Neck: V-neck",
      "Print or Pattern Type: Solid",
      "Surface Styling: Lace inserts",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "55% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    category: "dresses-gowns",
  },
  2: {
    id: 2,
    name: "Women’s Mustard Yellow Printed Anarkali Kurti",
    price: "₹899",
    originalPrice: "₹1635",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2-2.webp",
    ],
    desc: "Step out in style with this elegant yellow and solid print Anarkali gown, perfect for any occasion. Crafted from soft and breathable rayon fabric, it ensures all-day comfort. Featuring a self-design pattern that adds texture and depth, this kurti is a single-piece combo that stands out. The yellow color with floral motifs is both striking and versatile, making it a great addition to your ethnic collection.",
    details: [
      "Color: Yellow",
      "Fabric: Rayon",
      "Fit/Shape: Kaftan",
      "Length: Calf Length",
      "Neck: Surplice",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "45% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  3: {
    id: 3,
    name: "Women’s Navy Blue Floral Printed Anarkali Kurti",
    price: "₹799",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3-3.webp",
    ],
    desc: "Elegant ANNEIV Women Printed Viscose Rayon Anarkali Kurta featuring a beautiful floral print. Crafted from soft viscose rayon fabric for all-day comfort. Perfect for parties and special occasions with its classic Anarkali silhouette and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Floral",
      "Combo of: Single",
      "Ornamentation: Show Button",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL", "4XL", "5XL", "6XL"],
    category: "dresses-gowns",
  },
  4: {
    id: 4,
    name: "DARK GREEN Color Long Solid Border Tussle Tie Anarkali Kurti",
    price: "₹849",
    originalPrice: "₹1100",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4-4.webp",
    ],
    desc: "Elevate your ethnic wardrobe with this dark green solid border tussle tie Anarkali kurti. Crafted from premium rayon fabric, it offers a perfect blend of traditional charm and modern elegance. Ideal for festive occasions and social gatherings.",
    details: [
      "Color: Green",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Occasion: Festive",
      "Brand: MEESORRA",
      "Country of Origin: India",
    ],
    discount: "23% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  5: {
    id: 5,
    name: "Women’s White & Olive Printed Plus Size Kurti",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5-5.webp",
    ],
    desc: "Elegant cream-colored ethnic motif kurti crafted from soft rayon fabric. Features a regular fit with three-quarter sleeves and a classic V-neck. Perfect for daily wear and casual outings.",
    details: [
      "Color: Cream",
      "Fabric: Rayon",
      "Fit/Shape: Short Kurti",
      "Length: Above Knee",
      "Neck: V-neck",
      "Print or Pattern Type: Ethnic Motif",
      "Combo of: Single",
      "Ornamentation: Not Applicable",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Daily",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  6: {
    id: 6,
    name: "Women’s Sage Green Floral Printed Plus Size Kurti",
    price: "₹559",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6-6.webp",
    ],
    desc: "DMP314 Aqual Blue Color Printed Top crafted from soft rayon fabric. Features a flared fit with three-quarter sleeves and a stylish tie-up neck. Perfect for casual occasions with its beautiful floral print and tassel detailing.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Regular",
      "Neck/Collar: Tie-Up Neck",
      "Sleeve Styling: Regular Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Tassels",
      "Country of Origin: India",
    ],
    discount: "30% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  7: {
    id: 7,
    name: "Modern Flare Teal Kurti Top",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7-7.webp",
    ],
    desc: "NYPA Casual 3/4 Sleeve Printed Women Top crafted from soft rayon fabric. Features an empire fit with stylish bell sleeves and a notch neck. The striped floral print and pleated surface styling make it perfect for casual outings.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Empire",
      "Length: Regular",
      "Neck/Collar: Notch",
      "Sleeve Styling: Bell Sleeves",
      "Print or Pattern Type: Striped",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Pleated Or Rathered",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["S", "M", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  8: {
    id: 8,
    name: "Royal Red Floral Elegance",
    price: "₹399",
    originalPrice: "₹499",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8-8.webp",
    ],
    desc: "Maroon Color Rayon Gold Printed Top for Women. Features a beautiful A-line fit with mandarin collar and roll-up sleeves. The floral print and sheen surface styling make it perfect for casual occasions.",
    details: [
      "Color: Maroon",
      "Fabric: Rayon",
      "Fit/Shape: A-Line",
      "Length: Long",
      "Neck/Collar: Mandarin Collar",
      "Sleeve Styling: Roll-Up Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Sheen",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  9: {
    id: 9,
    name: "Sunshine Peach Casual T‑Shirt",
    price: "₹439",
    originalPrice: "₹550",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9-9.webp",
    ],
    desc: "Plush Womens Cotton Regular fit Printed Long Tshirt crafted from comfortable cotton blend fabric. Features a regular fit with short sleeves and round neck. The typography print adds a trendy touch, perfect for casual everyday wear.",
    details: [
      "Color: Peach",
      "Fabric: Cotton Blend",
      "Fit/Shape: Regular",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    availableSizes: ["4XL"],
    category: "tops-tees",
  },
  10: {
    id: 10,
    name: "Duchess Women Long top",
    price: "₹599",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10-10.webp",
    ],
    desc: "Duchess Women's Long top with simple round neck and short sleeves. Features side pockets with side slits, perfect for casual everyday wear, sports wear and night wear. Easy washable poly-cotton fabric with 60% cotton for best comfort.",
    details: [
      "Color: Black",
      "Fabric: Cotton Blend",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  11: {
    id: 11,
    name: "Women Plus Size Dark Blue Denim Jogger Jeans with Drawstring",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11-11.webp",
    ],
    desc: "Premium jogger-style jeans crafted from heavy washed denim fabric. Features a mid-rise waist, side taping, and a clean look with stretchable comfort. Perfect for casual and everyday wear with a trendy jogger fit.",
    details: [
      "Color: Navy Blue",
      "Fabric: Denim",
      "Fit/Shape: Jogger",
      "Length: Cropped",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Side Taping",
      "Shade: Dark",
      "Wash: Light Wash",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["32", "34", "36", "38", "40", "42"],
    category: "bottomwear",
  },
  12: {
    id: 12,
    name: "Ira Premium Joggers Washed Blue Jean For Women",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12-12.webp",
    ],
    desc: "Premium jogger-style jeans crafted from washed denim fabric. Features a mid-rise waist, fringed surface styling, and stretchable comfort for a relaxed fit. Perfect for casual everyday wear with a trendy jogger silhouette.",
    details: [
      "Color: Blue",
      "Fabric: Denim",
      "Fit/Shape: Jogger",
      "Length: Cropped",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Fringed",
      "Shade: Medium",
      "Wash: Light Wash",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["32", "34", "36", "38", "40", "42"],
    category: "bottomwear",
  },
  13: {
    id: 13,
    name: "Side Button Dark Blue Women Regular Mid Rise Blue Jeans Curvy Washed Loose Fit Denim Cargo Jeans for Women & Girls",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13-13.webp",
    ],
    desc: "Curvy washed loose-fit denim cargo jeans crafted from high-quality stretchable denim. Features a mid-rise waist, side buttons, fringed surface styling, and a baggy fit. Perfect for plus-size curvy women with heavy hips and thighs, suitable for party and office wear.",
    details: [
      "Color: Navy Blue",
      "Fabric: Denim",
      "Fit/Shape: Baggy",
      "Length: Regular",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Fringed",
      "Shade: Dark",
      "Wash: Light Wash",
      "Brand: NEUNK",
      "Generic Name: Jeans",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["36", "38", "40", "42", "44", "46"],
    category: "bottomwear",
  },
  14: {
    id: 14,
    name: "Women’s Navy Blue Embellished Flared Palazzo",
    price: "₹550",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14-14.webp",
    ],
    desc: "Fashionable Fashionista Women Palazzos crafted from soft rayon fabric with beautiful embroidery and mirror work. Features a wide leg flared fit with elastic waist band for comfortable wear. Perfect for casual and festive occasions.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Wide Leg/Flared",
      "Length: Full Length",
      "Waist Rise: Mid Rise",
      "Print or Pattern Type: Embellished",
      "Surface Styling: Embellishments",
      "Net Quantity (N): 1",
      "Waist closure: Drawstring",
      "Pattern: Embellished",
      "Country of Origin: India",
    ],
    discount: "21% off",
    sizes: [
      "26",
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40",
      "42",
      "44",
      "46",
      "Free Size",
    ],
    category: "bottomwear",
  },
  15: {
    id: 15,
    name: "Women’s Black Floral Print Flared Palazzo",
    price: "₹559",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15-15.webp",
    ],
    desc: "Upgrade your ethnic and casual wardrobe with these beautifully designed floral printed palazzo pants. Crafted with a soft and breathable fabric, these palazzos offer all-day comfort while maintaining a stylish and elegant look. The eye-catching multicolor floral pattern on a light base adds a refreshing charm, making it perfect for both casual outings and festive occasions. Designed with a high-rise elastic waistband and flared wide-leg silhouette for maximum comfort and graceful movement.",
    details: [
      "Color: Pink",
      "Fabric: Cotton Blend",
      "Fit/Shape: Pleated",
      "Length: Full Length",
      "Waist Rise: Mid Rise",
      "Print or Pattern Type: Solid",
      "Surface Styling: Taping/piping",
      "Net Quantity (N): 1",
      "Waist closure: Elastic waistband",
      "Pattern: Printed",
      "Generic Name: Palazzos",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL", "Free Size"],
    category: "bottomwear",
  },
  16: {
    id: 16,
    name: "Maroon Printed Maternity Maxi Dress",
    price: "₹450",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16-16.webp",
    ],
    desc: "Rayon Feeding Kurti for Women crafted from soft viscose rayon fabric. Features a comfortable A-line fit with V-neck and three-quarter sleeves. Designed with a front zipper closure for easy nursing access. Perfect for daily wear during maternity with its stylish printed pattern and calf length design.",
    details: [
      "Fit/Shape: A-line",
      "Neck: V-neck",
      "Length: Calf Length",
      "Pattern: Printed",
      "Fabric: Viscose Rayon",
      "Print or Pattern Type: Stripe",
      "Color: Maroon",
      "Combo of: Single",
      "Ornamentation: Not Applicable",
      "Occasion: Daily",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Front Zipper",
      "Included Components: FEEDING KURTI",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "36% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    category: "kurti-topwear",
  },
  17: {
    id: 17,
    name: "Women Grey Rayon Flared Maternity and Feeding Kurta Set",
    price: "₹650",
    originalPrice: "₹950",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17-17.webp",
    ],
    desc: "Women Grey Rayon flared maternity and feeding kurta set with both side zippers, 3/4 sleeves, sweetheart neckline and flared design. Pant comes with one side pocket and drawstring waistband. Perfect maternity cord set for women, suitable for office wear and daily use.",
    details: [
      "Fit/Shape: Flared",
      "Neck: V-neck",
      "Length: Above Knee",
      "Pattern: Printed",
      "Fabric: Rayon",
      "Print or Pattern Type: Floral",
      "Color: Grey",
      "Combo of: Single",
      "Bottomwear Fabric: Rayon",
      "Ornamentation: Not Applicable",
      "Occasion: Maternity",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: Pants",
      "Bottomwear Color: Grey",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Front Zipper",
      "Country of Origin: India",
    ],
    discount: "32% off",
    sizes: ["S", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
  18: {
    id: 18,
    name: "Maternity Feeding Kurti Set with Zippers – Comfortable Top & Bottom",
    price: "₹800",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18-18.webp",
    ],
    desc: "Women's Maternity Dress Feeding Kurti With Zippers (Top & Bottom) crafted from soft rayon fabric with beautiful floral print. Features invisible zipped breastfeeding slit for convenient nursing, 3/4 sleeves, round neck and above knee length. Designed to hide pre & post pregnancy baby bump beautifully. Comes with matching rayon pyjamas bottom with drawstring waistband. Perfect for baby showers, parties and daily wear.",
    details: [
      "Fit/Shape: Maternity",
      "Neck: Round",
      "Length: Above Knee",
      "Pattern: Printed",
      "Fabric: Rayon",
      "Print or Pattern Type: Floral",
      "Color: Yellow",
      "Combo of: Single",
      "Bottomwear Fabric: Rayon",
      "Ornamentation: Not Applicable",
      "Occasion: Daily",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: Pyjamas",
      "Bottomwear Color: Yellow",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Tie-Up",
      "Included Components: Top & Bottom set with 2 side Zip",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
  19: {
    id: 19,
    name: "Women Brown Heart Print Maternity & Feeding Set",
    price: "₹750",
    originalPrice: "₹1000",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19-19.webp",
    ],
    desc: "Kekabu Women's Printed Maternity & Feeding Top thoughtfully designed to provide comfort, style, and convenience for expecting and new mothers. Made from soft, breathable cotton fabric with smart feeding access design that allows easy and discreet breastfeeding anytime. Features short sleeves, relaxed comfort fit, and elegant printed design suitable for daily wear, home use, casual outings, and hospital visits.",
    details: [
      "Combo of: Single",
      "Sleeve Length: Short Sleeves",
      "Fit/Shape: Maternity",
      "Fabric: Cotton",
      "Neck: Round",
      "Color: Brown",
      "Print or Pattern Type: Abstract",
      "Length: Above Knee",
      "Bottom Type: Trousers",
      "Sleeve Styling: Regular",
      "Bottomwear Color: Brown",
      "Stitch Type: Stitched",
      "Ornamentation: Not Applicable",
      "Occasion: Maternity",
      "Bottomwear Fabric: Cotton",
      "Pattern: Printed",
      "Closure Type: Side Zipper",
      "Included Components: Top and pyjama",
      "Generic Name: Feeding Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "kurti-topwear",
  },
  20: {
    id: 20,
    name: "Women’s Printed Maternity & Feeding Midi Dress",
    price: "₹520",
    originalPrice: "₹1000",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20-20.webp",
    ],
    desc: "Soft maternity and nursing kurti made from flowy and lightweight viscose rayon fabric. Features a convenient feeding design with 2 discreet zippers for easy baby feeding. Elegant gathered styling with three-quarter sleeves, shirt neck and calf length. Snap button closure for easy wear. Perfect for maternity wear and breastfeeding after delivery, suitable for ethnic or casual occasions.",
    details: [
      "Fit/Shape: Maternity",
      "Neck: Shirt",
      "Length: Calf Length",
      "Pattern: Printed",
      "Fabric: Viscose Rayon",
      "Print or Pattern Type: Botanical",
      "Color: White",
      "Combo of: Single",
      "Bottomwear Fabric: No Bottomwear",
      "Ornamentation: Gathered",
      "Occasion: Photoshoot",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: No Bottomwear",
      "Bottomwear Color: No Bottomwear",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Snap Button",
      "Included Components: NA",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "48% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    availableSizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
  21: {
    id: 21,
    name: "NYPA ComfortFit Nursing Bra – Back Support Edition",
    price: "₹436",
    originalPrice: "₹715",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21-21.webp",
    ],
    desc: "SELECTIVE MATERIAL: 95% Cotton + 5% Spandex. This nursing bra for breastfeeding is made of high-quality combed cotton, not only ensures softness and high elasticity, and the breathable weave makes this bra more skin-friendly. Front snap closure for easy nursing access, seamless design for comfort and support.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Cotton",
      "Net Quantity (N): 1",
      "Seam Style: Seamless",
      "Color: Green",
      "Country of Origin: India",
    ],
    discount: "39% off",
    sizes: [
      "30A",
      "30B",
      "30C",
      "32A",
      "32B",
      "32C",
      "34A",
      "34B",
      "34C",
      "M",
      "L",
      "XL",
    ],
    availableSizes: [
      "30A",
      "30B",
      "30C",
      "32A",
      "32B",
      "32C",
      "34A",
      "34B",
      "34C",
      "M",
      "L",
      "XL",
    ],
    category: "feeding-bras",
  },
  22: {
    id: 22,
    name: "BRIELLE Women's Cotton Feeding Bra/Maternity/Nursing Bra Non-Padded Wire-Free Maternity Bra for (Pack of 3)",
    price: "₹580",
    originalPrice: "₹1260",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22-22.webp",
    ],
    desc: "Most important for pregnancy or nursing is comfortable and convenience, this nursing bra features wireless cup, non-padded, adjustable straps, one-step feeding clasp. Hooks can easily modify the width of the bra if you need and easy to snap on and off quickly. Sewn ergonomically with supportive stitching design that provides full coverage to your breasts.",
    details: [
      "Coverage: Full",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamed",
      "Color: Black",
      "Brand: Brielle",
      "Country of Origin: India",
    ],
    discount: "52% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  23: {
    id: 23,
    name: "Women's Cotton Multicolor Full Cup Non Padded Feeding Bra/Nursing Bra/Maternity Bra Combo - Pack of 3",
    price: "₹630",
    originalPrice: "₹1600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23-23.webp",
    ],
    desc: "Non-Padded Feeding Bra crafted from soft, breathable cotton blend fabric. Features full cup coverage, seamless design, easy one-hand clasp for quick nursing access, non-slip shoulder straps, and U-shaped back for better comfort and secure fit. Perfect for pregnancy and breastfeeding.",
    details: [
      "Coverage: Full",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamed",
      "Color: Multicolor",
      "Brand: ZIELEN",
      "Generic Name: Feeding Bra",
      "Country of Origin: India",
    ],
    discount: "61% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  24: {
    id: 24,
    name: "Non-Padded Wirefree Cotton Nursing Bra (Pack of 3) with Easy Drop-Down Cups & Back Hook Support",
    price: "₹710",
    originalPrice: "₹1320",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24-24.webp",
    ],
    desc: "Soft cotton bra for daily use, breathable breastfeeding bra combo pack of 3. Non-padded maternity bra with front hook closure, smooth soft fabric molds to your changing shape for comfortable wear during pregnancy, night, or nursing.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Polycotton",
      "Net Quantity (N): 3",
      "Seam Style: Seamless",
      "Color: Green",
      "Generic Name: Feeding Bra",
      "Included Components: COMBO OF 3PCS BRA",
      "Country of Origin: India",
    ],
    discount: "46% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    availableSizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  25: {
    id: 25,
    name: "Pack of 2 Soft Cotton Blend Front Open Daily Wear Bra for Women",
    price: "₹799",
    originalPrice: "₹1600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25-25.webp",
    ],
    desc: "Pack of 2 soft cotton blend front open daily wear bras for women. Padded, non-wired, seamed design with full coverage, front closure, and regular straps. Perfect for everyday comfort and casual wear.",
    details: [
      "Fabric: Cotton",
      "Color: Purple",
      "Net Quantity (N): 2",
      "Padding: Padded",
      "Type: Short Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Self-Design",
      "Closure: Front Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "50% off",
    sizes: ["36A", "36B", "38A", "38B", "40A", "40B", "XL", "XXL"],
    availableSizes: ["36A", "36B", "38A", "38B", "40A", "40B", "XL", "XXL"],
    category: "feeding-bras",
  },
  26: {
    id: 26,
    name: "Sylish women printed padded bra (pack of 3)",
    price: "₹399",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp"],
    desc: "Sylish women printed padded bra pack of 3. Made from cotton blend fabric with floral print. Lightly padded push-up design with three-quarter coverage. Features seamless construction, non-wired support, back closure, removable straps, and bow detailing. Perfect for everyday wear.",
    details: [
      "Fabric: Cotton Blend",
      "Color: White",
      "Net Quantity (N): 3",
      "Padding: Lightly",
      "Type: Push-Up",
      "Coverage: Three-quarter",
      "Print or Pattern Type: Floral",
      "Closure: Back Closure",
      "Straps: Removeable",
      "Surface Styling: Bows",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: [
      "28A",
      "28B",
      "30A",
      "30B",
      "32A",
      "32B",
      "34A",
      "34B",
      "36A",
      "36B",
      "38A",
      "38B",
      "40A",
      "40B",
    ],
    category: "bras",
  },
  27: {
    id: 27,
    name: "ZOFIT Pack of 2: Women’s Seamless Lightly Padded Sports & Everyday Cotton Bra",
    price: "₹599",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp"],
    desc: "ZOFIT Pack of 2 women’s seamless lightly padded sports & everyday cotton bra. Soft breathable cotton blend with seamless construction, light padding, wire-free design, and adjustable straps. Perfect for workouts and daily wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 2",
      "Padding: Padded",
      "Type: Long Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Slip-on",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Pads",
      "Brand: ZOFIT",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: [
      "28A",
      "28B",
      "28C",
      "28D",
      "30A",
      "30B",
      "30C",
      "30D",
      "32A",
      "32B",
      "32C",
      "32D",
      "34A",
      "34B",
      "S",
      "M",
      "L",
      "Free Size",
    ],
    category: "bras",
  },
  28: {
    id: 28,
    name: "Stylish Striped Padded Bra for Women | Comfortable Daily Wear Lingerie",
    price: "₹410",
    originalPrice: "₹699",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp"],
    desc: "Striped Padded T-Shirt Bra for women with smooth cups for a seamless look under outfits. Crafted from a soft cotton blend fabric that is gentle on skin and perfect for daily wear. Features a trendy striped design, non-wired support for lift and all-day comfort, back closure and regular straps with bow detailing.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Pink",
      "Net Quantity (N): 3",
      "Padding: Padded",
      "Type: Tshirt Bra",
      "Coverage: Full",
      "Print or Pattern Type: Striped",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "41% off",
    sizes: ["28B", "30B", "32B", "34B", "36B", "38B", "40B"],
    category: "bras",
  },
  29: {
    id: 29,
    name: "Pink Cotton Lycra Magic Bra – Full Coverage, Non-Wired, Non-Padded, Back Closure ",
    price: "₹499",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp"],
    desc: "This front closure bra is a mix of cotton lycra enabling a breathable fabric to stay away from sweat stains. Regular full support cotton lycra brushed double layered fabric front open magic bra, with no seams, pads and wire promising a no bounce look. Its full coverage provides maximum support and no spillage from top and sides.",
    details: [
      "Fabric: Lycra",
      "Color: Pink",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Front Open/Front Button Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: [
      "32B",
      "32C",
      "32D",
      "34B",
      "34C",
      "34D",
      "36B",
      "36C",
      "36D",
      "38B",
      "38C",
      "38D",
      "40B",
      "40C",
      "40D",
      "42B",
      "42C",
      "42D",
      "44B",
      "44C",
      "44D",
    ],
    category: "bras",
  },
  30: {
    id: 30,
    name: "Everyday Black Bra – Full Coverage, No-Bounce, Non-Wired Non-Padded, Back Closure",
    price: "₹499",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp"],
    desc: "This bra is ideal for all your outfit needs. From ethnic to western clothing, this will give you a side and back smoothening sleek look under your clothes. Crafted from soft cotton blend fabric with full coverage, seamed construction and non-wired support for all-day comfort.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Black",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Everyday Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Brand: MAROON",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: [
      "32B",
      "32C",
      "32D",
      "32E",
      "32F",
      "34B",
      "34C",
      "34D",
      "34E",
      "34F",
      "36B",
      "36C",
      "36D",
      "36E",
      "36F",
      "38B",
      "38C",
      "38D",
      "38E",
      "38F",
      "40B",
      "40C",
      "40D",
      "40E",
      "40F",
      "42B",
      "42C",
      "42D",
      "42E",
      "42F",
      "44B",
      "44C",
      "44D",
      "44E",
      "44F",
    ],
    category: "bras",
  },
  31: {
    id: 31,
    name: "Pack of 3 Multicolour High Waist Cotton Panties with Lace Design",
    price: "₹399",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/31.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/31.webp"],
    desc: "Pack of 3 multicolour high waist cotton panties for women with a delicate lace design. Soft, breathable cotton blend fabric with mid-rise fit and bikini shape for all-day comfort.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Black",
      "Net Quantity (N): 3",
      "Fit/ Shape: Bikini",
      "Pattern: Self-Design",
      "Print or Pattern Type: Stripe",
      "Waist Rise: Mid Rise",
      "Surface Styling: Bow",
      "Occasion: Fancy",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "34% off",
    sizes: ["S", "M", "L", "XL", "28", "30", "32", "34"],
    category: "panties",
  },
  32: {
    id: 32,
    name: "Pack of 3 Malai Lycra Printed Hipster Panties for Women – Multicolour, Everyday Wear",
    price: "₹250",
    originalPrice: "₹400",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/32.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/32.webp"],
    desc: "Pack of 3 Malai lycra printed hipster panties for women in soft modal fabric. Mid-rise, breathable and comfortable for everyday wear.",
    details: [
      "Fabric: Modal",
      "Color: Multicolor",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Abstract",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Brand: Miles Of Style",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "38% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  33: {
    id: 33,
    name: "Cymrite Pack of 3 Cotton Hipster Panties for Women – Floral Print, Everyday Wear",
    price: "₹350",
    originalPrice: "₹450",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/33.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/33.webp"],
    desc: "Cymrite pack of 3 cotton hipster panties for women with a soft floral print. Mid-rise, breathable cotton fabric for comfortable everyday wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Floral",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "22% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  34: {
    id: 34,
    name: "Cymrite Pack of 3 Modal Hipster Panties for Women – Quirky Print, Everyday Wear",
    price: "₹439",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/34.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/34.webp"],
    desc: "Cymrite pack of 3 modal hipster panties for women with a fun quirky print. Mid-rise, soft cotton fabric for comfortable everyday wear.",
    details: [
      "Fabric: Cotton",
      "Color: Purple",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Quirky",
      "Waist Rise: Mid Rise",
      "Occasion: Everyday",
      "Brand: Cymrite",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "45% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  35: {
    id: 35,
    name: "Women Pure Cotton Hipster Panties Combo Pack of 6 – Soft Breathable Daily Wear, Multicolor",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/35.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/35.webp"],
    desc: "Combo pack of 6 pure cotton hipster panties for women with a soft, breathable stretchable waistband. Skin-friendly, full-coverage and comfortable for all-day daily wear.",
    details: [
      "Fabric: Cotton",
      "Color: Navy Blue",
      "Net Quantity (N): 6",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Floral",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["75cm", "80cm", "85cm", "90cm", "95cm", "100cm", "105cm", "110cm", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    category: "panties",
  },
};

export type Item = (typeof items)[keyof typeof items];
