export const items = {
  1: {
    id: 1,
    name: "Women’s Teal Blue Flared Anarkali Kurti with Lace Sleeves",
    price: "₹549",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1-1.webp",
    ],
    desc: "Attractive women dress in crepe fabric with lace inserts. Fit and flare maxi dress with V-neck and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Crepe",
      "Fit/Shape: Fit and Flare",
      "Length: Maxi",
      "Neck: V-neck",
      "Print or Pattern Type: Solid",
      "Surface Styling: Lace inserts",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "55% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    category: "dresses-gowns",
  },
  2: {
    id: 2,
    name: "Women’s Mustard Yellow Printed Anarkali Kurti",
    price: "₹899",
    originalPrice: "₹1635",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2-2.webp",
    ],
    desc: "Step out in style with this elegant yellow and solid print Anarkali gown, perfect for any occasion. Crafted from soft and breathable rayon fabric, it ensures all-day comfort. Featuring a self-design pattern that adds texture and depth, this kurti is a single-piece combo that stands out. The yellow color with floral motifs is both striking and versatile, making it a great addition to your ethnic collection.",
    details: [
      "Color: Yellow",
      "Fabric: Rayon",
      "Fit/Shape: Kaftan",
      "Length: Calf Length",
      "Neck: Surplice",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "45% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  3: {
    id: 3,
    name: "Women’s Navy Blue Floral Printed Anarkali Kurti",
    price: "₹799",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3-3.webp",
    ],
    desc: "Elegant ANNEIV Women Printed Viscose Rayon Anarkali Kurta featuring a beautiful floral print. Crafted from soft viscose rayon fabric for all-day comfort. Perfect for parties and special occasions with its classic Anarkali silhouette and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Floral",
      "Combo of: Single",
      "Ornamentation: Show Button",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL", "4XL", "5XL", "6XL"],
    category: "dresses-gowns",
  },
  4: {
    id: 4,
    name: "DARK GREEN Color Long Solid Border Tussle Tie Anarkali Kurti",
    price: "₹849",
    originalPrice: "₹1100",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4-4.webp",
    ],
    desc: "Elevate your ethnic wardrobe with this dark green solid border tussle tie Anarkali kurti. Crafted from premium rayon fabric, it offers a perfect blend of traditional charm and modern elegance. Ideal for festive occasions and social gatherings.",
    details: [
      "Color: Green",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Occasion: Festive",
      "Brand: MEESORRA",
      "Country of Origin: India",
    ],
    discount: "23% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  5: {
    id: 5,
    name: "Women’s White & Olive Printed Plus Size Kurti",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5-5.webp",
    ],
    desc: "Elegant cream-colored ethnic motif kurti crafted from soft rayon fabric. Features a regular fit with three-quarter sleeves and a classic V-neck. Perfect for daily wear and casual outings.",
    details: [
      "Color: Cream",
      "Fabric: Rayon",
      "Fit/Shape: Short Kurti",
      "Length: Above Knee",
      "Neck: V-neck",
      "Print or Pattern Type: Ethnic Motif",
      "Combo of: Single",
      "Ornamentation: Not Applicable",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Daily",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  6: {
    id: 6,
    name: "Women’s Sage Green Floral Printed Plus Size Kurti",
    price: "₹559",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6-6.webp",
    ],
    desc: "DMP314 Aqual Blue Color Printed Top crafted from soft rayon fabric. Features a flared fit with three-quarter sleeves and a stylish tie-up neck. Perfect for casual occasions with its beautiful floral print and tassel detailing.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Regular",
      "Neck/Collar: Tie-Up Neck",
      "Sleeve Styling: Regular Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Tassels",
      "Country of Origin: India",
    ],
    discount: "30% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  7: {
    id: 7,
    name: "Modern Flare Teal Kurti Top",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7-7.webp",
    ],
    desc: "NYPA Casual 3/4 Sleeve Printed Women Top crafted from soft rayon fabric. Features an empire fit with stylish bell sleeves and a notch neck. The striped floral print and pleated surface styling make it perfect for casual outings.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Empire",
      "Length: Regular",
      "Neck/Collar: Notch",
      "Sleeve Styling: Bell Sleeves",
      "Print or Pattern Type: Striped",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Pleated Or Rathered",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["S", "M", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  8: {
    id: 8,
    name: "Royal Red Floral Elegance",
    price: "₹399",
    originalPrice: "₹499",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8-8.webp",
    ],
    desc: "Maroon Color Rayon Gold Printed Top for Women. Features a beautiful A-line fit with mandarin collar and roll-up sleeves. The floral print and sheen surface styling make it perfect for casual occasions.",
    details: [
      "Color: Maroon",
      "Fabric: Rayon",
      "Fit/Shape: A-Line",
      "Length: Long",
      "Neck/Collar: Mandarin Collar",
      "Sleeve Styling: Roll-Up Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Sheen",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  9: {
    id: 9,
    name: "Sunshine Peach Casual T‑Shirt",
    price: "₹439",
    originalPrice: "₹550",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9-9.webp",
    ],
    desc: "Plush Womens Cotton Regular fit Printed Long Tshirt crafted from comfortable cotton blend fabric. Features a regular fit with short sleeves and round neck. The typography print adds a trendy touch, perfect for casual everyday wear.",
    details: [
      "Color: Peach",
      "Fabric: Cotton Blend",
      "Fit/Shape: Regular",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    availableSizes: ["4XL"],
    category: "tops-tees",
  },
  10: {
    id: 10,
    name: "Duchess Women Long top",
    price: "₹599",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10-10.webp",
    ],
    desc: "Duchess Women's Long top with simple round neck and short sleeves. Features side pockets with side slits, perfect for casual everyday wear, sports wear and night wear. Easy washable poly-cotton fabric with 60% cotton for best comfort.",
    details: [
      "Color: Black",
      "Fabric: Cotton Blend",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
};

export type Item = (typeof items)[keyof typeof items];
