export const products = {
  4: {
    id: 4,
    name: "Anarkali Suit Women",
    price: "₹1200",
    originalPrice: "₹2700",
    image: "https://tinyurl.com/womwn",
    images: [
      "https://tinyurl.com/womwn",
      "https://tinyurl.com/hdfjsh",
      "https://tinyurl.com/youonrun",
      "https://tinyurl.com/tangolonh",
    ],
    desc: "Kurti set with dupatta - Cotton kurta set with dupatta. Women Embroidery Bollywood Style Kurta and Pant set with Dupatta.",
    details: ["Bottom Type: Pants", "Fit/Shape: A-line", "Print/Pattern Type: Floral", "Kurta Fabric: Cotton Blend", "Additional Details: Bottomwear Fabric: Cotton Blend", "Kurta Color: Purple", "Bottomwear Color: Purple", "Set Type: Kurta With Dupatta And Bottomwear", "Dupatta Fabric: Cotton Silk", "Dupatta Color: Purple", "Stitch Type: Stitched", "Length: Calf Length", "Neck: V-neck", "Sleeve Length: Three-Quarter Sleeves", "Sleeve Styling: Regular", "Pattern: Embroidered", "Ornamentation: Embroidered", "Net Quantity (N): Single", "Occasion: Party", "Brand: Fashion Mint", "Country of Origin: India"],
    discount: "56% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "dresses-gowns",
  },
   5: {
    id: 5,
    name: "Anarkali Suit Women - Purple",
    price: "₹1200",
    originalPrice: "₹2700",
    image: "https://images.meesho.com/images/products/530603959/irh0a_512.avif?width=512",
    images: [
      "https://images.meesho.com/images/products/530603959/irh0a_512.avif?width=512",
      "https://images.meesho.com/images/products/530603959/bpzhj_512.avif?width=512",
      "https://images.meesho.com/images/products/530603959/c9lrx_512.avif?width=512",
    ],
    desc: "Kurti set with dupatta - Cotton kurta set with dupatta. Women Embroidery Bollywood Style Kurta and Pant set with Dupatta.",
    details: ["Bottom Type: Pants", "Fit/Shape: A-line", "Print/Pattern Type: Floral", "Kurta Fabric: Cotton Blend", "Additional Details: Bottomwear Fabric: Cotton Blend", "Kurta Color: Purple", "Bottomwear Color: Purple", "Set Type: Kurta With Dupatta And Bottomwear", "Dupatta Fabric: Cotton Silk", "Dupatta Color: Purple", "Stitch Type: Stitched", "Length: Calf Length", "Neck: V-neck", "Sleeve Length: Three-Quarter Sleeves", "Sleeve Styling: Regular", "Pattern: Embroidered", "Ornamentation: Embroidered", "Net Quantity (N): Single", "Occasion: Party", "Brand: Fashion Mint", "Country of Origin: India"],
    discount: "56% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "dresses-gowns",
  },
   6: {
    id: 6,
    name: "Daily Wear Kurti (Combo Pack 6 Kurta)",
    price: "₹1200",
    originalPrice: "₹2700",
    image: "https://images.meesho.com/images/products/347210675/hlddp_512.avif?width=512",
    images: [
      "https://images.meesho.com/images/products/347210675/hdbmi_512.avif?width=512",
      "https://images.meesho.com/images/products/347210675/wfbiq_512.avif?width=512",
      "https://images.meesho.com/images/products/347210675/hlddp_512.avif?width=512",
      "https://images.meesho.com/images/products/347210675/gyz0z_512.avif?width=512",
    ],
    desc: "Printed Crepe Straight Festival Kurti Wear - Combo Pack of 6 Kurtas",
    details: ["Color: Green", "Fabric: Poly Crepe", "Fit/Shape: A-line", "Length: Calf Length", "Neck: Round", "Print/Pattern Type: Ethnic Motif", "Combo of: Combo of 6", "Ornamentation: Cutouts", "Stitch Type: Stitched", "Sleeve Length: Three-Quarter Sleeves", "Sleeve Styling: Regular", "Pattern: Printed", "Occasion: Daily", "Brand: Glamson", "Country of Origin: India"],
    discount: "56% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
   7: {
    id: 7,
    name: "Traditional Cotton Ajrakh Printed Kurti For Women",
    price: "₹1200",
    originalPrice: "₹2400",
    image: "https://images.meesho.com/images/products/499906523/ldgd8_512.avif?width=512",
    images: [
      "https://images.meesho.com/images/products/499906523/ldgd8_512.avif?width=512",
      "https://images.meesho.com/images/products/499906523/fl2ch_512.avif?width=512",
      "https://images.meesho.com/images/products/499906523/ksvu0_512.avif?width=512",
      "https://images.meesho.com/images/products/499906523/krsu2_512.avif?width=512",
    ],
    desc: "Traditional Cotton Ajrakh Printed Kurti For Women - Black Color",
    details: ["Color: Black", "Fabric: Cotton Cambric", "Fit/Shape: Straight", "Length: Calf Length", "Neck: Round", "Print/Pattern Type: Floral", "Combo of: Single", "Ornamentation: Tassels and Latkans", "Stitch Type: Stitched", "Sleeve Length: Three-Quarter Sleeves", "Sleeve Styling: Regular", "Pattern: Printed", "Occasion: Daily", "Generic Name: Kurtis", "Country of Origin: India"],
    discount: "82% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL", "6XL"],
    category: "tops-tees",
  },
   8: {
    id: 8,
    name: "Women Kurta",
    price: "₹1200",
    originalPrice: "₹2400",
    image: "https://images.meesho.com/images/products/149834633/saqqo_512.avif?width=512",
    images: [
      "https://images.meesho.com/images/products/149834633/saqqo_512.avif?width=512",
      "https://images.meesho.com/images/products/149834633/saqq__512.avif?width=512",
      "https://images.meesho.com/images/products/149834633/8qhpq_512.avif?width=64",
      "https://images.meesho.com/images/products/149834633/btwcl_512.avif?width=512",
    ],
    desc: "Women Kurta - Rayon fabric, Anarkali fit, Mint Green color. Perfect for daily wear.",
    details: ["Color: Mint Green", "Fabric: Rayon", "Fit/Shape: Anarkali", "Length: Ankle Length", "Neck: Mandarin", "Print/Pattern Type: Floral", "Combo of: Single", "Ornamentation: Show Button", "Stitch Type: Stitched", "Sleeve Length: Three-Quarter Sleeves", "Sleeve Styling: Regular", "Pattern: Printed", "Occasion: Daily", "Generic Name: Kurtis", "Country of Origin: India"],
    discount: "65% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
   9: {
    id: 9,
    name: "Stylish Women Fancy Dresses l Casual & Party Wear",
    price: "₹297",
    originalPrice: "₹599",
    image: "https://images.meesho.com/images/products/426443566/jvzf7_512.avif?width=512",
    images: [
      "https://images.meesho.com/images/products/426443566/jvzf7_512.avif?width=512",
      "https://images.meesho.com/images/products/426443566/oarod_512.avif?width=512",
      "https://images.meesho.com/images/products/426443566/xlshv_512.avif?width=512",
      "https://images.meesho.com/images/products/426443566/nsahw_512.avif?width=512",
    ],
    desc: "Trendy western wear long frock for girls and women, party wear, stylish wear, birthday wear, festive wear, comfortable wear for women, better quality at low price.",
    details: ["Color: Black", "Fabric: Cotton Blend", "Fit/Shape: Fit and Flare", "Length: Maxi", "Neck: Square Neck", "Print or Pattern Type: Floral", "Surface Styling: Pleated or Gathered", "Occasion: Casual", "Sleeve Length: Short Sleeves", "Sleeve Styling: Regular", "Pattern: Printed", "Net Quantity (N): 1", "Add On: No Add on", "Character: Not Applicable", "TYPE: One Piece", "Generic Name: Dresses", "Country of Origin: India"],
    discount: "50% off",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "dresses-gowns",
  },
};

export type Product = typeof products[keyof typeof products];
