export const items = {
  11: {
    id: 11,
    name: "Women Plus Size Dark Blue Denim Jogger Jeans with Drawstring",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/11-11.webp",
    ],
    desc: "Premium jogger-style jeans crafted from heavy washed denim fabric. Features a mid-rise waist, side taping, and a clean look with stretchable comfort. Perfect for casual and everyday wear with a trendy jogger fit.",
    details: [
      "Color: Navy Blue",
      "Fabric: Denim",
      "Fit/Shape: Jogger",
      "Length: Cropped",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Side Taping",
      "Shade: Dark",
      "Wash: Light Wash",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["32", "34", "36", "38", "40", "42"],
    category: "bottomwear",
  },
  12: {
    id: 12,
    name: "Ira Premium Joggers Washed Blue Jean For Women",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/12-12.webp",
    ],
    desc: "Premium jogger-style jeans crafted from washed denim fabric. Features a mid-rise waist, fringed surface styling, and stretchable comfort for a relaxed fit. Perfect for casual everyday wear with a trendy jogger silhouette.",
    details: [
      "Color: Blue",
      "Fabric: Denim",
      "Fit/Shape: Jogger",
      "Length: Cropped",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Fringed",
      "Shade: Medium",
      "Wash: Light Wash",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["32", "34", "36", "38", "40", "42"],
    category: "bottomwear",
  },
  13: {
    id: 13,
    name: "Side Button Dark Blue Women Regular Mid Rise Blue Jeans Curvy Washed Loose Fit Denim Cargo Jeans for Women & Girls",
    price: "₹850",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/13-13.webp",
    ],
    desc: "Curvy washed loose-fit denim cargo jeans crafted from high-quality stretchable denim. Features a mid-rise waist, side buttons, fringed surface styling, and a baggy fit. Perfect for plus-size curvy women with heavy hips and thighs, suitable for party and office wear.",
    details: [
      "Color: Navy Blue",
      "Fabric: Denim",
      "Fit/Shape: Baggy",
      "Length: Regular",
      "Waist Rise: Mid Rise",
      "Stretch: Stretchable",
      "Distress: Clean Look",
      "Surface Styling: Fringed",
      "Shade: Dark",
      "Wash: Light Wash",
      "Brand: NEUNK",
      "Generic Name: Jeans",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["36", "38", "40", "42", "44", "46"],
    category: "bottomwear",
  },
  14: {
    id: 14,
    name: "Women's Navy Blue Embellished Flared Palazzo",
    price: "₹550",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/14-14.webp",
    ],
    desc: "Fashionable Fashionista Women Palazzos crafted from soft rayon fabric with beautiful embroidery and mirror work. Features a wide leg flared fit with elastic waist band for comfortable wear. Perfect for casual and festive occasions.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Wide Leg/Flared",
      "Length: Full Length",
      "Waist Rise: Mid Rise",
      "Print or Pattern Type: Embellished",
      "Surface Styling: Embellishments",
      "Net Quantity (N): 1",
      "Waist closure: Drawstring",
      "Pattern: Embellished",
      "Country of Origin: India",
    ],
    discount: "21% off",
    sizes: ["26", "28", "30", "32", "34", "36", "38", "40", "42", "44", "46", "Free Size"],
    category: "bottomwear",
  },
  15: {
    id: 15,
    name: "Women's Black Floral Print Flared Palazzo",
    price: "₹559",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/15-15.webp",
    ],
    desc: "Upgrade your ethnic and casual wardrobe with these beautifully designed floral printed palazzo pants. Crafted with a soft and breathable fabric, these palazzos offer all-day comfort while maintaining a stylish and elegant look. The eye-catching multicolor floral pattern on a light base adds a refreshing charm, making it perfect for both casual outings and festive occasions. Designed with a high-rise elastic waistband and flared wide-leg silhouette for maximum comfort and graceful movement.",
    details: [
      "Color: Pink",
      "Fabric: Cotton Blend",
      "Fit/Shape: Pleated",
      "Length: Full Length",
      "Waist Rise: Mid Rise",
      "Print or Pattern Type: Solid",
      "Surface Styling: Taping/piping",
      "Net Quantity (N): 1",
      "Waist closure: Elastic waistband",
      "Pattern: Printed",
      "Generic Name: Palazzos",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL", "Free Size"],
    category: "bottomwear",
  },
};

export type Item = (typeof items)[keyof typeof items];
