export const items = {
  26: {
    id: 26,
    name: "Sylish women printed padded bra (pack of 3)",
    price: "₹399",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp"],
    desc: "Sylish women printed padded bra pack of 3. Made from cotton blend fabric with floral print. Lightly padded push-up design with three-quarter coverage. Features seamless construction, non-wired support, back closure, removable straps, and bow detailing. Perfect for everyday wear.",
    details: [
      "Fabric: Cotton Blend",
      "Color: White",
      "Net Quantity (N): 3",
      "Padding: Lightly",
      "Type: Push-Up",
      "Coverage: Three-quarter",
      "Print or Pattern Type: Floral",
      "Closure: Back Closure",
      "Straps: Removeable",
      "Surface Styling: Bows",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["28A", "28B", "30A", "30B", "32A", "32B", "34A", "34B", "36A", "36B", "38A", "38B", "40A", "40B"],
    category: "bras",
  },
  27: {
    id: 27,
    name: "ZOFIT Pack of 2: Women's Seamless Lightly Padded Sports & Everyday Cotton Bra",
    price: "₹599",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp"],
    desc: "ZOFIT Pack of 2 women's seamless lightly padded sports & everyday cotton bra. Soft breathable cotton blend with seamless construction, light padding, wire-free design, and adjustable straps. Perfect for workouts and daily wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 2",
      "Padding: Padded",
      "Type: Long Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Slip-on",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Pads",
      "Brand: ZOFIT",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["28A", "28B", "28C", "28D", "30A", "30B", "30C", "30D", "32A", "32B", "32C", "32D", "34A", "34B", "S", "M", "L", "Free Size"],
    category: "bras",
  },
  28: {
    id: 28,
    name: "Stylish Striped Padded Bra for Women | Comfortable Daily Wear Lingerie",
    price: "₹410",
    originalPrice: "₹699",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp"],
    desc: "Striped Padded T-Shirt Bra for women with smooth cups for a seamless look under outfits. Crafted from a soft cotton blend fabric that is gentle on skin and perfect for daily wear. Features a trendy striped design, non-wired support for lift and all-day comfort, back closure and regular straps with bow detailing.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Pink",
      "Net Quantity (N): 3",
      "Padding: Padded",
      "Type: Tshirt Bra",
      "Coverage: Full",
      "Print or Pattern Type: Striped",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "41% off",
    sizes: ["28B", "30B", "32B", "34B", "36B", "38B", "40B"],
    category: "bras",
  },
  29: {
    id: 29,
    name: "Pink Cotton Lycra Magic Bra – Full Coverage, Non-Wired, Non-Padded, Back Closure",
    price: "₹499",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp"],
    desc: "This front closure bra is a mix of cotton lycra enabling a breathable fabric to stay away from sweat stains. Regular full support cotton lycra brushed double layered fabric front open magic bra, with no seams, pads and wire promising a no bounce look. Its full coverage provides maximum support and no spillage from top and sides.",
    details: [
      "Fabric: Lycra",
      "Color: Pink",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Front Open/Front Button Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: ["32B", "32C", "32D", "34B", "34C", "34D", "36B", "36C", "36D", "38B", "38C", "38D", "40B", "40C", "40D", "42B", "42C", "42D", "44B", "44C", "44D"],
    category: "bras",
  },
  30: {
    id: 30,
    name: "Everyday Black Bra – Full Coverage, No-Bounce, Non-Wired Non-Padded, Back Closure",
    price: "₹499",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp"],
    desc: "This bra is ideal for all your outfit needs. From ethnic to western clothing, this will give you a side and back smoothening sleek look under your clothes. Crafted from soft cotton blend fabric with full coverage, seamed construction and non-wired support for all-day comfort.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Black",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Everyday Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Brand: MAROON",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["32B", "32C", "32D", "32E", "32F", "34B", "34C", "34D", "34E", "34F", "36B", "36C", "36D", "36E", "36F", "38B", "38C", "38D", "38E", "38F", "40B", "40C", "40D", "40E", "40F", "42B", "42C", "42D", "42E", "42F", "44B", "44C", "44D", "44E", "44F"],
    category: "bras",
  },
};

export type Item = (typeof items)[keyof typeof items];
