export const items = {
  26: {
    id: 26,
    name: "Sylish women printed padded bra (pack of 3)",
    price: "₹399",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/26.webp"],
    desc: "Sylish women printed padded bra pack of 3. Made from cotton blend fabric with floral print. Lightly padded push-up design with three-quarter coverage. Features seamless construction, non-wired support, back closure, removable straps, and bow detailing. Perfect for everyday wear.",
    details: [
      "Fabric: Cotton Blend",
      "Color: White",
      "Net Quantity (N): 3",
      "Padding: Lightly",
      "Type: Push-Up",
      "Coverage: Three-quarter",
      "Print or Pattern Type: Floral",
      "Closure: Back Closure",
      "Straps: Removeable",
      "Surface Styling: Bows",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: [
      "28A",
      "28B",
      "30A",
      "30B",
      "32A",
      "32B",
      "34A",
      "34B",
      "36A",
      "36B",
      "38A",
      "38B",
      "40A",
      "40B",
    ],
    category: "bras",
  },
  27: {
    id: 27,
    name: "ZOFIT Pack of 2: Women's Seamless Lightly Padded Sports & Everyday Cotton Bra",
    price: "₹599",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/27.webp"],
    desc: "ZOFIT Pack of 2 women's seamless lightly padded sports & everyday cotton bra. Soft breathable cotton blend with seamless construction, light padding, wire-free design, and adjustable straps. Perfect for workouts and daily wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 2",
      "Padding: Padded",
      "Type: Long Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Slip-on",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Pads",
      "Brand: ZOFIT",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: [
      "28A",
      "28B",
      "28C",
      "28D",
      "30A",
      "30B",
      "30C",
      "30D",
      "32A",
      "32B",
      "32C",
      "32D",
      "34A",
      "34B",
      "S",
      "M",
      "L",
      "Free Size",
    ],
    category: "bras",
  },
  28: {
    id: 28,
    name: "Stylish Striped Padded Bra for Women | Comfortable Daily Wear Lingerie",
    price: "₹410",
    originalPrice: "₹699",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/28.webp"],
    desc: "Striped Padded T-Shirt Bra for women with smooth cups for a seamless look under outfits. Crafted from a soft cotton blend fabric that is gentle on skin and perfect for daily wear. Features a trendy striped design, non-wired support for lift and all-day comfort, back closure and regular straps with bow detailing.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Pink",
      "Net Quantity (N): 3",
      "Padding: Padded",
      "Type: Tshirt Bra",
      "Coverage: Full",
      "Print or Pattern Type: Striped",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "41% off",
    sizes: ["28B", "30B", "32B", "34B", "36B", "38B", "40B"],
    category: "bras",
  },
  29: {
    id: 29,
    name: "Pink Cotton Lycra Magic Bra – Full Coverage, Non-Wired, Non-Padded, Back Closure",
    price: "₹499",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/29.webp"],
    desc: "This front closure bra is a mix of cotton lycra enabling a breathable fabric to stay away from sweat stains. Regular full support cotton lycra brushed double layered fabric front open magic bra, with no seams, pads and wire promising a no bounce look. Its full coverage provides maximum support and no spillage from top and sides.",
    details: [
      "Fabric: Lycra",
      "Color: Pink",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Front Open/Front Button Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: [
      "32B",
      "32C",
      "32D",
      "34B",
      "34C",
      "34D",
      "36B",
      "36C",
      "36D",
      "38B",
      "38C",
      "38D",
      "40B",
      "40C",
      "40D",
      "42B",
      "42C",
      "42D",
      "44B",
      "44C",
      "44D",
    ],
    category: "bras",
  },
  30: {
    id: 30,
    name: "Everyday Black Bra – Full Coverage, No-Bounce, Non-Wired Non-Padded, Back Closure",
    price: "₹499",
    originalPrice: "₹599",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/30.webp"],
    desc: "This bra is ideal for all your outfit needs. From ethnic to western clothing, this will give you a side and back smoothening sleek look under your clothes. Crafted from soft cotton blend fabric with full coverage, seamed construction and non-wired support for all-day comfort.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Black",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Everyday Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Bows",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Hooks",
      "Brand: MAROON",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: [
      "32B",
      "32C",
      "32D",
      "32E",
      "32F",
      "34B",
      "34C",
      "34D",
      "34E",
      "34F",
      "36B",
      "36C",
      "36D",
      "36E",
      "36F",
      "38B",
      "38C",
      "38D",
      "38E",
      "38F",
      "40B",
      "40C",
      "40D",
      "40E",
      "40F",
      "42B",
      "42C",
      "42D",
      "42E",
      "42F",
      "44B",
      "44C",
      "44D",
      "44E",
      "44F",
    ],
    category: "bras",
  },
  61: {
    id: 61,
    name: "Women Push-up Lightly Padded Bra",
    price: "₹460",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/61.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/61.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/61-61.webp",
    ],
    desc: "Women Push-up Lightly Padded Bra from Bahucharaji Creation. Made from nylon fabric with seamless construction and lightly padded push-up design. Features half coverage, back closure, strapless bandeau style, non-wired support, and removable pads. Perfect for everyday wear.",
    details: [
      "Fabric: Nylon",
      "Color: Beige",
      "Net Quantity (N): 1",
      "Padding: Padded",
      "Type: Bandeau/Tube Bra",
      "Coverage: Half",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Strapless",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Pads",
      "Country of Origin: India",
    ],
    discount: "34% off",
    sizes: ["30A", "30B", "32A", "32B", "34A", "34B"],
    category: "bras",
  },
  62: {
    id: 62,
    name: "Full Coverage Backless Cotton Bra for Women",
    price: "₹390",
    originalPrice: "₹680",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/62.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/62.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/62-62.webp",
    ],
    desc: "Full Coverage Backless Cotton Bra for Women. Backless non-padded t-shirt bra with full coverage, seamless construction, non-wired support, back closure, regular adjustable straps, and transparent strap & band free design. Perfect for everyday wear and casual outfits.",
    details: [
      "Fabric: Cotton",
      "Color: Beige",
      "Net Quantity (N): 1",
      "Padding: Non Padded",
      "Type: Tshirt Bra",
      "Coverage: Full",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: Straps",
      "Brand: BEWILD",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "43% off",
    sizes: [
      "28B",
      "28C",
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
    ],
    category: "bras",
  },
  63: {
    id: 63,
    name: "Hot Sale Ice Silk Triangle Cup Tube Top Bra",
    price: "₹340",
    originalPrice: "₹520",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/63.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/63.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/63-63.webp",
    ],
    desc: "Hot sale ice silk triangle cup tube top bra for women. Lightweight cool summer innerwear with half coverage, padded design, seamed construction, non-wired support, and back closure. Perfect for fancy occasions and casual wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 1",
      "Padding: Padded",
      "Type: Bikini Bra",
      "Coverage: Half",
      "Print or Pattern Type: Solid",
      "Closure: Back Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Fancy",
      "Add On: No Add on",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "35% off",
    sizes: ["28A", "28B", "30A", "30B", "32A", "32B", "S", "M", "Free Size"],
    category: "bras",
  },
   64: {
     id: 64,
     name: "Raha S.G Lightly Padded Full Coverage T-Shirt Bra for Women",
     price: "₹390",
     originalPrice: "₹700",
     image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/64.webp",
     images: [
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/64.webp",
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/64-64.webp",
     ],
     desc: "Raha S.G Lightly Padded Full Coverage T-Shirt Bra for Women. Experience all-day comfort and a smooth silhouette with this seamless molded cup bra. Crafted from soft cotton blend fabric with three-quarter coverage, non-wired support, back closure, and adjustable regular straps. Perfect for daily wear and fitted outfits.",
     details: [
       "Fabric: Cotton Blend",
       "Color: Navy Blue",
       "Net Quantity (N): 1",
       "Padding: Lightly",
       "Type: Tshirt Bra",
       "Coverage: Three-quarter",
       "Print or Pattern Type: Solid",
       "Closure: Back Closure",
       "Straps: Regular",
       "Seam Style: Seamless",
       "Wiring: Non Wired",
       "Occasion: Everyday",
       "Add On: No Add on",
       "Brand: RAHA S.G",
       "Generic Name: Bra",
       "Country of Origin: India",
     ],
     discount: "44% off",
     sizes: ["30B", "32B", "34B", "36B", "38B"],
     category: "bras",
   },
   65: {
     id: 65,
     name: "Women's Full Coverage Padded T-shirt Bra in Trendy Cute Heart Print",
     price: "₹549",
     originalPrice: "₹800",
     image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/65.webp",
     images: [
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/65.webp",
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/65-65.webp",
     ],
     desc: "Women's Full Coverage Padded T-shirt Bra in Trendy Cute Heart Print. Seamless Lycra Spandex fabric bra with heavily padded support for a smooth look under T-shirts and kurti. Features full coverage, back closure, regular straps, bow detailing, and wire-free construction. Perfect for everyday wear and western outfits.",
     details: [
       "Fabric: Lycra",
       "Color: Brown",
       "Net Quantity (N): 1",
       "Padding: Heavy",
       "Type: Everyday/Hook Bra",
       "Coverage: Full",
       "Print or Pattern Type: All Over Print",
       "Closure: Back Closure",
       "Straps: Regular",
       "Surface Styling: Bows",
       "Seam Style: Seamless",
       "Wiring: Non Wired",
       "Occasion: Everyday",
       "Add On: No Add on",
       "Brand: YOUTORI LOVE",
       "Generic Name: Bra",
       "Country of Origin: India",
     ],
     discount: "31% off",
     sizes: ["30B", "30C", "32B", "32C", "34B", "34C", "36B", "36C", "38B", "38C", "40B", "40C"],
     category: "bras",
   },
 };

export type Item = (typeof items)[keyof typeof items];
