export const items = {
  1: {
    id: 1,
    name: "Women's Teal Blue Flared Anarkali Kurti with Lace Sleeves",
    price: "₹549",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/1-1.webp",
    ],
    desc: "Attractive women dress in crepe fabric with lace inserts. Fit and flare maxi dress with V-neck and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Crepe",
      "Fit/Shape: Fit and Flare",
      "Length: Maxi",
      "Neck: V-neck",
      "Print or Pattern Type: Solid",
      "Surface Styling: Lace inserts",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "55% off",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    category: "dresses-gowns",
  },
  2: {
    id: 2,
    name: "Women's Mustard Yellow Printed Anarkali Kurti",
    price: "₹899",
    originalPrice: "₹1635",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/2-2.webp",
    ],
    desc: "Step out in style with this elegant yellow and solid print Anarkali gown, perfect for any occasion. Crafted from soft and breathable rayon fabric, it ensures all-day comfort. Featuring a self-design pattern that adds texture and depth, this kurti is a single-piece combo that stands out. The yellow color with floral motifs is both striking and versatile, making it a great addition to your ethnic collection.",
    details: [
      "Color: Yellow",
      "Fabric: Rayon",
      "Fit/Shape: Kaftan",
      "Length: Calf Length",
      "Neck: Surplice",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "45% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  3: {
    id: 3,
    name: "Women's Navy Blue Floral Printed Anarkali Kurti",
    price: "₹799",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/3-3.webp",
    ],
    desc: "Elegant Women Printed Viscose Rayon Anarkali Kurta featuring a beautiful floral print. Crafted from soft viscose rayon fabric for all-day comfort. Perfect for parties and special occasions with its classic Anarkali silhouette and three-quarter sleeves.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Floral",
      "Combo of: Single",
      "Ornamentation: Show Button",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL", "4XL", "5XL", "6XL"],
    category: "dresses-gowns",
  },
  4: {
    id: 4,
    name: "DARK GREEN Color Long Solid Border Tussle Tie Anarkali Kurti",
    price: "₹849",
    originalPrice: "₹1100",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/4-4.webp",
    ],
    desc: "Elevate your ethnic wardrobe with this dark green solid border tussle tie Anarkali kurti. Crafted from premium rayon fabric, it offers a perfect blend of traditional charm and modern elegance. Ideal for festive occasions and social gatherings.",
    details: [
      "Color: Green",
      "Fabric: Rayon",
      "Fit/Shape: Anarkali",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Occasion: Festive",
      "Brand: MEESORRA",
      "Country of Origin: India",
    ],
    discount: "23% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  5: {
    id: 5,
    name: "Women's White & Olive Printed Plus Size Kurti",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/5-5.webp",
    ],
    desc: "Elegant cream-colored ethnic motif kurti crafted from soft rayon fabric. Features a regular fit with three-quarter sleeves and a classic V-neck. Perfect for daily wear and casual outings.",
    details: [
      "Color: Cream",
      "Fabric: Rayon",
      "Fit/Shape: Short Kurti",
      "Length: Above Knee",
      "Neck: V-neck",
      "Print or Pattern Type: Ethnic Motif",
      "Combo of: Single",
      "Ornamentation: Not Applicable",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Daily",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  36: {
    id: 36,
    name: "Fashion Zest Rayon Green Color Plus size Gown",
    price: "₹999",
    originalPrice: "₹1250",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/36.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/36.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/36-36.webp",
    ],
    desc: "The most Hit One Green Gown now in Plus size. The Ankle length Gown printed with latest trend which will keep you in pleasant mood. It looks stunning every time you match it with other accessories. The green colour is very beautiful which will give a rich sense and style to you.",
    details: [
      "Color: Green",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Calf Length",
      "Neck: Notch",
      "Print or Pattern Type: Botanical",
      "Combo of: Single",
      "Ornamentation: Tassels and Latkans",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Daily",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: [
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
      "9XL",
      "10XL",
    ],
    category: "dresses-gowns",
  },
  37: {
    id: 37,
    name: "Woman Printed Embroidey Flar Gown Rama",
    price: "₹670",
    originalPrice: "₹910",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/37.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/37.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/37-37.webp",
    ],
    desc: "Woman Printed Embroidey Flar Gown Rama crafted from soft rayon fabric. Features a flared fit with three-quarter sleeves and round neck. The beautiful floral print and frill detailing make it perfect for daily wear.",
    details: [
      "Color: Green",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Ankle Length",
      "Neck: Round",
      "Print or Pattern Type: Floral",
      "Combo of: Single",
      "Ornamentation: Frills",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Daily",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "26% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL", "6XL", "7XL"],
    category: "dresses-gowns",
  },
  38: {
    id: 38,
    name: "Women's Plus Size Rayon Golden Buti Printed A-line Kurta",
    price: "₹899",
    originalPrice: "₹1150",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/38.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/38.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/38-38.webp",
    ],
    desc: "Women's Plus Size Rayon Golden Buti Printed A-line Kurta crafted from soft viscose rayon fabric. Features an A-line fit with three-quarter sleeves and round neck. The golden buti print and gota work detailing make it perfect for party wear.",
    details: [
      "Color: Maroon",
      "Fabric: Viscose Rayon",
      "Fit/Shape: A-line",
      "Length: Calf Length",
      "Neck: Round",
      "Print or Pattern Type: Foil",
      "Combo of: Single",
      "Ornamentation: Gota Work",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Printed",
      "Occasion: Party",
      "Brand: YASH GALLERY",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "22% off",
    sizes: [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
    ],
    category: "dresses-gowns",
  },
  39: {
    id: 39,
    name: "Red Womens Cotton Bandhej Print Anarkali Kurta",
    price: "₹1050",
    originalPrice: "₹1400",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/39.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/39.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/39-39.webp",
    ],
    desc: "Red Womens Cotton Bandhej Print Anarkali Kurta (Red) crafted from soft cotton fabric. Features a panelled fit with three-quarter sleeves and round neck. The bandhej print and pintuck detailing make it perfect for party wear.",
    details: [
      "Color: Red",
      "Fabric: Cotton",
      "Fit/Shape: Panelled",
      "Length: Calf Length",
      "Neck: Round",
      "Print or Pattern Type: Solid",
      "Combo of: Single",
      "Ornamentation: Pintucks",
      "Stitch Type: Stitched",
      "Sleeve Length: Three-Quarter Sleeves",
      "Sleeve Styling: Regular",
      "Pattern: Solid",
      "Occasion: Party",
      "Generic Name: Kurtis",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "4XL",
      "5XL",
      "6XL",
      "7XL",
      "8XL",
    ],
    category: "dresses-gowns",
  },
  40: {
     id: 40,
     name: "Women Cotton Cambric Anarkali Gown",
     price: "₹999",
     originalPrice: "₹1200",
     image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/40.webp",
     images: [
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/40.webp",
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/40-40.webp",
     ],
     desc: "Elegant women cotton cambric Anarkali gown featuring embroidered surface styling and Ikat print. Perfect for casual wear with its flared Anarkali silhouette, round neck, and three-quarter bell sleeves. A single piece stitched garment with no dupatta or bottomwear.",
     details: [
       "Color: Blue",
       "Fabric: Cotton Cambric",
       "Fit/Shape: Anarkali",
       "Length: Maxi",
       "Neck: Round Neck",
       "Print or Pattern Type: Ikat",
       "Occasion: Casual Wear",
       "Dupatta Fabric: No Dupatta",
       "Sleeve Length: Three-Quarter Sleeves",
       "Net Quantity (N): 1",
       "Bottom Fabric: No Bottomwear",
       "Stitch Type: Stitched",
       "Inner Fabric: Cotton Cambric",
       "Pattern: Printed",
       "Bottom Color: No Bottomwear",
       "Set Type: Single piece",
       "Dupatta Color: No Dupatta",
       "Sleeve Styling: Bell",
       "Country of Origin: India",
     ],
     discount: "17% off",
     sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL"],
     category: "dresses-gowns",
   },
 };

export type Item = (typeof items)[keyof typeof items];
