export const items = {
  21: {
    id: 21,
    name: "NYPA ComfortFit Nursing Bra – Back Support Edition",
    price: "₹436",
    originalPrice: "₹715",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/21-21.webp",
    ],
    desc: "SELECTIVE MATERIAL: 95% Cotton + 5% Spandex. This nursing bra for breastfeeding is made of high-quality combed cotton, not only ensures softness and high elasticity, and the breathable weave makes this bra more skin-friendly. Front snap closure for easy nursing access, seamless design for comfort and support.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Cotton",
      "Net Quantity (N): 1",
      "Seam Style: Seamless",
      "Color: Green",
      "Country of Origin: India",
    ],
    discount: "39% off",
    sizes: [
      "30A",
      "30B",
      "30C",
      "32A",
      "32B",
      "32C",
      "34A",
      "34B",
      "34C",
      "M",
      "L",
      "XL",
    ],
    availableSizes: [
      "30A",
      "30B",
      "30C",
      "32A",
      "32B",
      "32C",
      "34A",
      "34B",
      "34C",
      "M",
      "L",
      "XL",
    ],
    category: "feeding-bras",
  },
  22: {
    id: 22,
    name: "BRIELLE Women's Cotton Feeding Bra/Maternity/Nursing Bra Non-Padded Wire-Free Maternity Bra for (Pack of 3)",
    price: "₹580",
    originalPrice: "₹1260",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/22-22.webp",
    ],
    desc: "Most important for pregnancy or nursing is comfortable and convenience, this nursing bra features wireless cup, non-padded, adjustable straps, one-step feeding clasp. Hooks can easily modify the width of the bra if you need and easy to snap on and off quickly. Sewn ergonomically with supportive stitching design that provides full coverage to your breasts.",
    details: [
      "Coverage: Full",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamed",
      "Color: Black",
      "Brand: Brielle",
      "Country of Origin: India",
    ],
    discount: "52% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  23: {
    id: 23,
    name: "Women's Cotton Multicolor Full Cup Non Padded Feeding Bra/Nursing Bra/Maternity Bra Combo - Pack of 3",
    price: "₹630",
    originalPrice: "₹1600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/23-23.webp",
    ],
    desc: "Non-Padded Feeding Bra crafted from soft, breathable cotton blend fabric. Features full cup coverage, seamless design, easy one-hand clasp for quick nursing access, non-slip shoulder straps, and U-shaped back for better comfort and secure fit. Perfect for pregnancy and breastfeeding.",
    details: [
      "Coverage: Full",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamed",
      "Color: Multicolor",
      "Brand: ZIELEN",
      "Generic Name: Feeding Bra",
      "Country of Origin: India",
    ],
    discount: "61% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  24: {
    id: 24,
    name: "Non-Padded Wirefree Cotton Nursing Bra (Pack of 3) with Easy Drop-Down Cups & Back Hook Support",
    price: "₹710",
    originalPrice: "₹1320",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/24-24.webp",
    ],
    desc: "Soft cotton bra for daily use, breathable breastfeeding bra combo pack of 3. Non-padded maternity bra with front hook closure, smooth soft fabric molds to your changing shape for comfortable wear during pregnancy, night, or nursing.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Polycotton",
      "Net Quantity (N): 3",
      "Seam Style: Seamless",
      "Color: Green",
      "Generic Name: Feeding Bra",
      "Included Components: COMBO OF 3PCS BRA",
      "Country of Origin: India",
    ],
    discount: "46% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    availableSizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  25: {
    id: 25,
    name: "Pack of 2 Soft Cotton Blend Front Open Daily Wear Bra for Women",
    price: "₹799",
    originalPrice: "₹1600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/25-25.webp",
    ],
    desc: "Pack of 2 soft cotton blend front open daily wear bras for women. Padded, non-wired, seamed design with full coverage, front closure, and regular straps. Perfect for everyday comfort and casual wear.",
    details: [
      "Fabric: Cotton",
      "Color: Purple",
      "Net Quantity (N): 2",
      "Padding: Padded",
      "Type: Short Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Self-Design",
      "Closure: Front Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamed",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Generic Name: Bra",
      "Country of Origin: India",
    ],
    discount: "50% off",
    sizes: ["36A", "36B", "38A", "38B", "40A", "40B", "XL", "XXL"],
    availableSizes: ["36A", "36B", "38A", "38B", "40A", "40B", "XL", "XXL"],
    category: "feeding-bras",
  },
  56: {
    id: 56,
    name: "Women's Front Open Cotton Bra with Dotted Print | Soft & Stretchable Daily Wear Non-Padded Bra",
    price: "₹670",
    originalPrice: "₹900",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/56.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/56.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/56-56.webp",
    ],
    desc: "Front open stylish innerwear designed for practical use throughout the week. Crafted using breathable cotton blend fabric that provides a relaxed fit for long hours. The dotted surface adds a modern and stylish appeal. Non-padded and wire-free, making it a great choice for routine usage. Secure button panel in front allows quick and hassle-free wear. Suitable for teens to adults, blending softness with smart design.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Grey",
      "Net Quantity (N): 2",
      "Padding: Lightly",
      "Type: Short Bralette",
      "Coverage: Full",
      "Print or Pattern Type: Micro",
      "Closure: Front Closure",
      "Straps: Regular",
      "Surface Styling: Not Applicable",
      "Seam Style: Seamless",
      "Wiring: Non Wired",
      "Occasion: Everyday",
      "Add On: No Add on",
      "Country of Origin: India",
    ],
    discount: "26% off",
    sizes: ["34B", "36B", "38B", "40B", "42B", "44B", "XXL", "XXXL"],
    category: "feeding-bras",
  },
  57: {
    id: 57,
    name: "Women & Girls Cotton Non-Padded C Cup Bra | Seamless Bralette | Full Coverage | Pack of 3",
    price: "₹430",
    originalPrice: "₹900",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/57.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/57.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/57-57.webp",
    ],
    desc: "Introducing the most comfortable everyday bra you will ever wear! Our 100% Pure Cotton Non-Padded C Cup Bra is specially designed for Women and Girls who believe that true comfort should never be compromised. Whether you are heading to school, college, office, or just relaxing at home — this bra is your perfect daily companion.",
    details: [
      "Coverage: Full",
      "Add On: Hooks",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamed",
      "Color: Blue",
      "Generic Name: Feeding Bra",
      "Included Components: BRA",
      "Country of Origin: India",
    ],
    discount: "52% off",
    sizes: ["30C", "32C", "34C", "36C", "38C", "40C", "42C", "44C"],
    category: "feeding-bras",
  },
  58: {
    id: 58,
    name: "Women's Cotton Non-Padded Premium Maternity/Feeding Bra (Pack of 3 Pieces)",
    price: "₹570",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/58.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/58.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/58-58.webp",
    ],
    desc: "Maternity Bra is designed for ease up breastfeeding with front clasps. Snug-fit under the band provides extra support to tender breasts. Features 3-row hooks for adjustable sizing, non-wired design for tender skin, soft cotton rich fabric (80% cotton, 20% polyester) that lets skin breathe, side stitches for extra support, and all day & night comfort. Clasps allow easy access feeding without removing the bra.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Cotton Blend",
      "Net Quantity (N): 3",
      "Seam Style: Seamless",
      "Color: Green",
      "Brand: PASQUALINA",
      "Generic Name: Feeding Bra",
      "Included Components: Pack of 3 pieces bra",
      "Country of Origin: India",
    ],
    discount: "29% off",
    sizes: [
      "30B",
      "30C",
      "32B",
      "32C",
      "34B",
      "34C",
      "36B",
      "36C",
      "38B",
      "38C",
      "40B",
      "40C",
      "42B",
      "42C",
      "44B",
      "44C",
    ],
    category: "feeding-bras",
  },
  59: {
    id: 59,
    name: "Evamomies Medium Coverage Non Padded & Wireless Maternity Bra",
    price: "₹700",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/59.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/59.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/59-59.webp",
    ],
    desc: "Evamomies Medium Coverage Non Padded & Wireless Maternity Bra designed for comfortable maternity and nursing support. Features seamless construction, soft modal fabric, and wireless design for all-day comfort during pregnancy and breastfeeding.",
    details: [
      "Coverage: Full",
      "Add On: No Add on",
      "Fabric: Modal",
      "Net Quantity (N): 1",
      "Seam Style: Seamless",
      "Color: Peach",
      "Generic Name: Feeding Bra",
      "Included Components: Pack of 1",
      "Country of Origin: India",
    ],
    discount: "42% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL"],
    category: "feeding-bras",
  },
  60: {
    id: 60,
    name: "Piftif Women's Padded, Non-Wired Nursing Bras for Breastfeeding Seamless Maternity Bra Ultra Comfort Smooth Wireless Pregnancy Sleeping Bralette",
    price: "₹634",
    originalPrice: "₹950",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/60.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/60.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/60-60.webp",
    ],
    desc: "3-in-1 Maternity/Sleep/Nursing Bra. Ultra comfort lycra material with excellent elasticity and service life. Stable triangle support design prevents sagging. Removable pads for customizable comfort. Seamless crossover design with cuttable stitches in the middle for convenient breastfeeding. Perfect for maternity, sleep, and nursing needs.",
    details: [
      "Coverage: Full",
      "Add On: Pads",
      "Net Quantity (N): 1",
      "Seam Style: Seamed",
      "Color: Grey",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["32D", "34C", "34D", "34DD", "34E", "36C", "36D", "36E", "38C", "38D", "38E", "40C", "40D", "40DD", "40E"],
    category: "feeding-bras",
  },
};

export type Item = (typeof items)[keyof typeof items];
