export const items = {
  16: {
    id: 16,
    name: "Maroon Printed Maternity Maxi Dress",
    price: "₹450",
    originalPrice: "₹700",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/16-16.webp",
    ],
    desc: "Rayon Feeding Kurti for Women crafted from soft viscose rayon fabric. Features a comfortable A-line fit with V-neck and three-quarter sleeves. Designed with a front zipper closure for easy nursing access. Perfect for daily wear during maternity with its stylish printed pattern and calf length design.",
    details: [
      "Fit/Shape: A-line",
      "Neck: V-neck",
      "Length: Calf Length",
      "Pattern: Printed",
      "Fabric: Viscose Rayon",
      "Print or Pattern Type: Stripe",
      "Color: Maroon",
      "Combo of: Single",
      "Ornamentation: Not Applicable",
      "Occasion: Daily",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Front Zipper",
      "Included Components: FEEDING KURTI",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "36% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    category: "kurti-topwear",
  },
  17: {
    id: 17,
    name: "Women Grey Rayon Flared Maternity and Feeding Kurta Set",
    price: "₹650",
    originalPrice: "₹950",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/17-17.webp",
    ],
    desc: "Women Grey Rayon flared maternity and feeding kurta set with both side zippers, 3/4 sleeves, sweetheart neckline and flared design. Pant comes with one side pocket and drawstring waistband. Perfect maternity cord set for women, suitable for office wear and daily use.",
    details: [
      "Fit/Shape: Flared",
      "Neck: V-neck",
      "Length: Above Knee",
      "Pattern: Printed",
      "Fabric: Rayon",
      "Print or Pattern Type: Floral",
      "Color: Grey",
      "Combo of: Single",
      "Bottomwear Fabric: Rayon",
      "Ornamentation: Not Applicable",
      "Occasion: Maternity",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: Pants",
      "Bottomwear Color: Grey",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Front Zipper",
      "Country of Origin: India",
    ],
    discount: "32% off",
    sizes: ["S", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
  18: {
    id: 18,
    name: "Maternity Feeding Kurti Set with Zippers – Comfortable Top & Bottom",
    price: "₹800",
    originalPrice: "₹1200",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/18-18.webp",
    ],
    desc: "Women's Maternity Dress Feeding Kurti With Zippers (Top & Bottom) crafted from soft rayon fabric with beautiful floral print. Features invisible zipped breastfeeding slit for convenient nursing, 3/4 sleeves, round neck and above knee length. Designed to hide pre & post pregnancy baby bump beautifully. Comes with matching rayon pyjamas bottom with drawstring waistband. Perfect for baby showers, parties and daily wear.",
    details: [
      "Fit/Shape: Maternity",
      "Neck: Round",
      "Length: Above Knee",
      "Pattern: Printed",
      "Fabric: Rayon",
      "Print or Pattern Type: Floral",
      "Color: Yellow",
      "Combo of: Single",
      "Bottomwear Fabric: Rayon",
      "Ornamentation: Not Applicable",
      "Occasion: Daily",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: Pyjamas",
      "Bottomwear Color: Yellow",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Tie-Up",
      "Included Components: Top & Bottom set with 2 side Zip",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "33% off",
    sizes: ["M", "L", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
  19: {
    id: 19,
    name: "Women Brown Heart Print Maternity & Feeding Set",
    price: "₹750",
    originalPrice: "₹1000",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/19-19.webp",
    ],
    desc: "Kekabu Women's Printed Maternity & Feeding Top thoughtfully designed to provide comfort, style, and convenience for expecting and new mothers. Made from soft, breathable cotton fabric with smart feeding access design that allows easy and discreet breastfeeding anytime. Features short sleeves, relaxed comfort fit, and elegant printed design suitable for daily wear, home use, casual outings, and hospital visits.",
    details: [
      "Combo of: Single",
      "Sleeve Length: Short Sleeves",
      "Fit/Shape: Maternity",
      "Fabric: Cotton",
      "Neck: Round",
      "Color: Brown",
      "Print or Pattern Type: Abstract",
      "Length: Above Knee",
      "Bottom Type: Trousers",
      "Sleeve Styling: Regular",
      "Bottomwear Color: Brown",
      "Stitch Type: Stitched",
      "Ornamentation: Not Applicable",
      "Occasion: Maternity",
      "Bottomwear Fabric: Cotton",
      "Pattern: Printed",
      "Closure Type: Side Zipper",
      "Included Components: Top and pyjama",
      "Generic Name: Feeding Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "kurti-topwear",
  },
  20: {
    id: 20,
    name: "Women's Printed Maternity & Feeding Midi Dress",
    price: "₹520",
    originalPrice: "₹1000",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/20-20.webp",
    ],
    desc: "Soft maternity and nursing kurti made from flowy and lightweight viscose rayon fabric. Features a convenient feeding design with 2 discreet zippers for easy baby feeding. Elegant gathered styling with three-quarter sleeves, shirt neck and calf length. Snap button closure for easy wear. Perfect for maternity wear and breastfeeding after delivery, suitable for ethnic or casual occasions.",
    details: [
      "Fit/Shape: Maternity",
      "Neck: Shirt",
      "Length: Calf Length",
      "Pattern: Printed",
      "Fabric: Viscose Rayon",
      "Print or Pattern Type: Botanical",
      "Color: White",
      "Combo of: Single",
      "Bottomwear Fabric: No Bottomwear",
      "Ornamentation: Gathered",
      "Occasion: Photoshoot",
      "Stitch Type: Stitched",
      "Sleeve Styling: Regular",
      "Bottom Type: No Bottomwear",
      "Bottomwear Color: No Bottomwear",
      "Sleeve Length: Three-Quarter Sleeves",
      "Closure Type: Snap Button",
      "Included Components: NA",
      "Generic Name: Maternity Kurtis & Kurta Sets",
      "Country of Origin: India",
    ],
    discount: "48% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    availableSizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "kurti-topwear",
  },
};

export type Item = (typeof items)[keyof typeof items];
