export const items = {
  31: {
    id: 31,
    name: "Pack of 3 Multicolour High Waist Cotton Panties with Lace Design",
    price: "₹399",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/31.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/31.webp"],
    desc: "Pack of 3 multicolour high waist cotton panties for women with a delicate lace design. Soft, breathable cotton blend fabric with mid-rise fit and bikini shape for all-day comfort.",
    details: [
      "Fabric: Cotton Blend",
      "Color: Black",
      "Net Quantity (N): 3",
      "Fit/ Shape: Bikini",
      "Pattern: Self-Design",
      "Print or Pattern Type: Stripe",
      "Waist Rise: Mid Rise",
      "Surface Styling: Bow",
      "Occasion: Fancy",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "34% off",
    sizes: ["S", "M", "L", "XL", "28", "30", "32", "34"],
    category: "panties",
  },
  32: {
    id: 32,
    name: "Pack of 3 Malai Lycra Printed Hipster Panties for Women – Multicolour, Everyday Wear",
    price: "₹250",
    originalPrice: "₹400",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/32.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/32.webp"],
    desc: "Pack of 3 Malai lycra printed hipster panties for women in soft modal fabric. Mid-rise, breathable and comfortable for everyday wear.",
    details: [
      "Fabric: Modal",
      "Color: Multicolor",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Abstract",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Brand: Miles Of Style",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "38% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  33: {
    id: 33,
    name: "Cymrite Pack of 3 Cotton Hipster Panties for Women – Floral Print, Everyday Wear",
    price: "₹350",
    originalPrice: "₹450",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/33.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/33.webp"],
    desc: "Cymrite pack of 3 cotton hipster panties for women with a soft floral print. Mid-rise, breathable cotton fabric for comfortable everyday wear.",
    details: [
      "Fabric: Cotton",
      "Color: Black",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Floral",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "22% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  34: {
    id: 34,
    name: "Cymrite Pack of 3 Modal Hipster Panties for Women – Quirky Print, Everyday Wear",
    price: "₹439",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/34.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/34.webp"],
    desc: "Cymrite pack of 3 modal hipster panties for women with a fun quirky print. Mid-rise, soft cotton fabric for comfortable everyday wear.",
    details: [
      "Fabric: Cotton",
      "Color: Purple",
      "Net Quantity (N): 3",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Quirky",
      "Waist Rise: Mid Rise",
      "Occasion: Everyday",
      "Brand: Cymrite",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "45% off",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    category: "panties",
  },
  35: {
    id: 35,
    name: "Women Pure Cotton Hipster Panties Combo Pack of 6 – Soft Breathable Daily Wear, Multicolor",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/35.webp",
    images: ["https://cdn.jsdelivr.net/gh/arbutani/web-img@main/35.webp"],
    desc: "Combo pack of 6 pure cotton hipster panties for women with a soft, breathable stretchable waistband. Skin-friendly, full-coverage and comfortable for all-day daily wear.",
    details: [
      "Fabric: Cotton",
      "Color: Navy Blue",
      "Net Quantity (N): 6",
      "Fit/ Shape: Hipster",
      "Pattern: Printed",
      "Print or Pattern Type: Floral",
      "Waist Rise: Mid Rise",
      "Surface Styling: Not Applicable",
      "Occasion: Everyday",
      "Generic Name: Panties",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["75cm", "80cm", "85cm", "90cm", "95cm", "100cm", "105cm", "110cm", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    category: "panties",
  },
};

export type Item = (typeof items)[keyof typeof items];
