export const items = {
  6: {
    id: 6,
    name: "Women's Sage Green Floral Printed Plus Size Kurti",
    price: "₹559",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6-6.webp",
    ],
    desc: "DMP314 Aqual Blue Color Printed Top crafted from soft rayon fabric. Features a flared fit with three-quarter sleeves and a stylish tie-up neck. Perfect for casual occasions with its beautiful floral print and tassel detailing.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Regular",
      "Neck/Collar: Tie-Up Neck",
      "Sleeve Styling: Regular Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Tassels",
      "Country of Origin: India",
    ],
    discount: "30% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  7: {
    id: 7,
    name: "Modern Flare Teal Kurti Top",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7-7.webp",
    ],
    desc: "NYPA Casual 3/4 Sleeve Printed Women Top crafted from soft rayon fabric. Features an empire fit with stylish bell sleeves and a notch neck. The striped floral print and pleated surface styling make it perfect for casual outings.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Empire",
      "Length: Regular",
      "Neck/Collar: Notch",
      "Sleeve Styling: Bell Sleeves",
      "Print or Pattern Type: Striped",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Pleated Or Rathered",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["S", "M", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  8: {
    id: 8,
    name: "Royal Red Floral Elegance",
    price: "₹399",
    originalPrice: "₹499",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8-8.webp",
    ],
    desc: "Maroon Color Rayon Gold Printed Top for Women. Features a beautiful A-line fit with mandarin collar and roll-up sleeves. The floral print and sheen surface styling make it perfect for casual occasions.",
    details: [
      "Color: Maroon",
      "Fabric: Rayon",
      "Fit/Shape: A-Line",
      "Length: Long",
      "Neck/Collar: Mandarin Collar",
      "Sleeve Styling: Roll-Up Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Sheen",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  9: {
    id: 9,
    name: "Sunshine Peach Casual T-Shirt",
    price: "₹439",
    originalPrice: "₹550",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9-9.webp",
    ],
    desc: "Plush Womens Cotton Regular fit Printed Long Tshirt crafted from comfortable cotton blend fabric. Features a regular fit with short sleeves and round neck. The typography print adds a trendy touch, perfect for casual everyday wear.",
    details: [
      "Color: Peach",
      "Fabric: Cotton Blend",
      "Fit/Shape: Regular",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    availableSizes: ["4XL"],
    category: "tops-tees",
  },
  10: {
    id: 10,
    name: "Duchess Women Long top",
    price: "₹599",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10-10.webp",
    ],
    desc: "Duchess Women's Long top with simple round neck and short sleeves. Features side pockets with side slits, perfect for casual everyday wear, sports wear and night wear. Easy washable poly-cotton fabric with 60% cotton for best comfort.",
    details: [
      "Color: Black",
      "Fabric: Cotton Blend",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  41: {
    id: 41,
    name: "Fancy Feminine Women Dresses, Frock_Top,Kurti_Top",
    price: "₹410",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/41.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/41.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/41-41.webp",
    ],
    desc: "Red color Flared Rayon 3/4 Sleeves Tie up(Pom-Pom) Hand Block Printed Top. Crafted from soft rayon fabric with a flared tunic fit, three-quarter sleeves, and stylish pom-pom tie-ups at the neck. The floral printed pattern makes it perfect for casual occasions.",
    details: [
      "Color: Black",
      "Fabric: Rayon",
      "Fit/Shape: Tunic",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Styling: Regular Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Tie-Ups",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "49% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    category: "tops-tees",
  },
    42: {
      id: 42,
      name: "IKRASS Women's Kantha Cotton Embroidered Regular Top (Blue)",
      price: "₹699",
      originalPrice: "₹999",
      image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/42.webp",
      images: [
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/42.webp",
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/42-42.webp",
      ],
      desc: "IKRASS Women's Kantha Cotton Embroidered Regular Top in Aqua Blue. Crafted from net fabric with a fitted regular fit, round neck, and flared short sleeves. Features beautiful embroidery with tie-up surface styling, perfect for party occasions.",
      details: [
        "Color: Aqua Blue",
        "Fabric: Net",
        "Fit/Shape: Fitted",
        "Length: Regular",
        "Neck/Collar: Round Neck",
        "Sleeve Styling: Flared Sleeves",
        "Print or Pattern Type: Solid",
        "Occasion: Party",
        "Sleeve Length: Short Sleeves",
        "Pattern: Embroidered",
        "Surface Styling: Tie-Ups",
        "Net Quantity (N): 1",
        "Generic Name: Tops & Tunics",
        "Country of Origin: India",
      ],
      discount: "30% off",
      sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL", "5XL"],
      category: "tops-tees",
    },
    43: {
      id: 43,
      name: "Pink Oversized T-Shirts for Women & Girls | Stylish Women's Printed Half Sleeve Tops",
      price: "₹370",
      originalPrice: "₹600",
      image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/43.webp",
      images: [
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/43.webp",
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/43-43.webp",
      ],
      desc: "Trendy Pink Oversized T-Shirts for Women & Girls. Crafted from soft cotton blend fabric with a regular fit, round neck, and short sleeves. Features stylish ethnic motif prints with knitted surface styling. Perfect for casual occasions, offering a comfortable and chic relaxed fit.",
      details: [
        "Color: Pink",
        "Fabric: Cotton Blend",
        "Fit/Shape: Regular",
        "Length: Regular",
        "Neck/Collar: Round Neck",
        "Sleeve Styling: Regular Sleeves",
        "Print or Pattern Type: Ethnic Motif",
        "Occasion: Casual",
        "Sleeve Length: Short Sleeves",
        "Pattern: Printed",
        "Surface Styling: Knitted",
        "Net Quantity (N): 1",
        "Brand: Trift Point",
        "Character: Tweety",
        "Generic Name: Tops & Tunics",
        "Country of Origin: India",
      ],
      discount: "38% off",
      sizes: ["XS", "S", "M", "L", "XL"],
      category: "tops-tees",
    },
    44: {
      id: 44,
      name: "Trendy Black Oversized T-Shirts for Women & Girls | Stylish Women's Printed Half Sleeve Tops",
      price: "₹350",
      originalPrice: "₹500",
      image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/44.webp",
      images: [
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/44.webp",
        "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/44-44.webp",
      ],
      desc: "Trendy Black Oversized T-Shirts for Women & Girls. Crafted from soft cotton blend fabric with a regular fit, round neck, and short sleeves. Features stylish typography prints with a relaxed streetwear vibe. Perfect for casual occasions, offering ultimate comfort and effortless cool.",
      details: [
        "Color: Black",
        "Fabric: Cotton Blend",
        "Fit/Shape: Regular",
        "Length: Regular",
        "Neck/Collar: Round Neck",
        "Sleeve Styling: Regular Sleeves",
        "Print or Pattern Type: Typography",
        "Occasion: Casual",
        "Sleeve Length: Short Sleeves",
        "Pattern: Printed",
        "Surface Styling: Not Applicable",
        "Net Quantity (N): 1",
        "Brand: Trift Point",
        "Character: Not Applicable",
        "Generic Name: Tops & Tunics",
        "Country of Origin: India",
      ],
      discount: "30% off",
      sizes: ["S", "M", "L", "XL"],
      category: "tops-tees",
    },
   45: {
     id: 45,
     name: "Urban Forge Women Black & White Striped Oversized T-Shirt | Stylish Casual Wear Top for Girls",
     price: "₹312",
     originalPrice: "₹400",
     image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/45.webp",
     images: [
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/45.webp",
       "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/45-45.webp",
     ],
     desc: "Urban Forge Women Black & White Striped Oversized T-Shirt. Crafted from soft cotton fabric with a regular fit, round neck, and short sleeves. Features stylish horizontal stripes with a relaxed oversized silhouette. Perfect for casual occasions, offering a comfortable and trendy streetwear look.",
     details: [
       "Color: Black",
       "Fabric: Cotton",
       "Fit/Shape: Regular",
       "Length: Regular",
       "Neck/Collar: Round Neck",
       "Sleeve Length: Short Sleeves",
       "Print or Pattern Type: Horizontal Stripes",
       "Net Quantity (N): 1",
       "Sleeve Styling: Regular Sleeves",
       "Pattern: Striped",
       "Surface Styling: Not Applicable",
       "Character: Not Applicable",
       "Generic Name: Tshirts",
       "Country of Origin: India",
     ],
     discount: "22% off",
     sizes: ["XS", "S", "M", "L", "XL", "XXL"],
     category: "tops-tees",
   },
};

export type Item = (typeof items)[keyof typeof items];
