export const items = {
  6: {
    id: 6,
    name: "Women's Sage Green Floral Printed Plus Size Kurti",
    price: "₹559",
    originalPrice: "₹800",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/6-6.webp",
    ],
    desc: "DMP314 Aqual Blue Color Printed Top crafted from soft rayon fabric. Features a flared fit with three-quarter sleeves and a stylish tie-up neck. Perfect for casual occasions with its beautiful floral print and tassel detailing.",
    details: [
      "Color: Navy Blue",
      "Fabric: Rayon",
      "Fit/Shape: Flared",
      "Length: Regular",
      "Neck/Collar: Tie-Up Neck",
      "Sleeve Styling: Regular Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Tassels",
      "Country of Origin: India",
    ],
    discount: "30% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  7: {
    id: 7,
    name: "Modern Flare Teal Kurti Top",
    price: "₹499",
    originalPrice: "₹600",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/7-7.webp",
    ],
    desc: "NYPA Casual 3/4 Sleeve Printed Women Top crafted from soft rayon fabric. Features an empire fit with stylish bell sleeves and a notch neck. The striped floral print and pleated surface styling make it perfect for casual outings.",
    details: [
      "Color: Blue",
      "Fabric: Rayon",
      "Fit/Shape: Empire",
      "Length: Regular",
      "Neck/Collar: Notch",
      "Sleeve Styling: Bell Sleeves",
      "Print or Pattern Type: Striped",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Pleated Or Rathered",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "17% off",
    sizes: ["S", "M", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
  8: {
    id: 8,
    name: "Royal Red Floral Elegance",
    price: "₹399",
    originalPrice: "₹499",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/8-8.webp",
    ],
    desc: "Maroon Color Rayon Gold Printed Top for Women. Features a beautiful A-line fit with mandarin collar and roll-up sleeves. The floral print and sheen surface styling make it perfect for casual occasions.",
    details: [
      "Color: Maroon",
      "Fabric: Rayon",
      "Fit/Shape: A-Line",
      "Length: Long",
      "Neck/Collar: Mandarin Collar",
      "Sleeve Styling: Roll-Up Sleeves",
      "Print or Pattern Type: Floral",
      "Occasion: Casual",
      "Sleeve Length: Three-Quarter Sleeves",
      "Pattern: Printed",
      "Surface Styling: Sheen",
      "Net Quantity (N): 1",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    category: "tops-tees",
  },
  9: {
    id: 9,
    name: "Sunshine Peach Casual T-Shirt",
    price: "₹439",
    originalPrice: "₹550",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/9-9.webp",
    ],
    desc: "Plush Womens Cotton Regular fit Printed Long Tshirt crafted from comfortable cotton blend fabric. Features a regular fit with short sleeves and round neck. The typography print adds a trendy touch, perfect for casual everyday wear.",
    details: [
      "Color: Peach",
      "Fabric: Cotton Blend",
      "Fit/Shape: Regular",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "20% off",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL", "4XL"],
    availableSizes: ["4XL"],
    category: "tops-tees",
  },
  10: {
    id: 10,
    name: "Duchess Women Long top",
    price: "₹599",
    originalPrice: "₹799",
    image: "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10.webp",
      "https://cdn.jsdelivr.net/gh/arbutani/web-img@main/10-10.webp",
    ],
    desc: "Duchess Women's Long top with simple round neck and short sleeves. Features side pockets with side slits, perfect for casual everyday wear, sports wear and night wear. Easy washable poly-cotton fabric with 60% cotton for best comfort.",
    details: [
      "Color: Black",
      "Fabric: Cotton Blend",
      "Length: Long",
      "Neck/Collar: Round Neck",
      "Sleeve Length: Short Sleeves",
      "Print or Pattern Type: Typography",
      "Net Quantity (N): 1",
      "Sleeve Styling: Regular Sleeves",
      "Pattern: Printed",
      "Country of Origin: India",
    ],
    discount: "25% off",
    sizes: ["L", "XL", "XXL", "XXXL", "4XL", "5XL"],
    category: "tops-tees",
  },
};

export type Item = (typeof items)[keyof typeof items];
